from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class ResumeForm(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    fullname = models.CharField(max_length=100)
    jobTitle = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    ph = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    portfolio = models.CharField(max_length=100)
    siteLabel = models.CharField(max_length=100)
    facebook = models.CharField(max_length=100)
    fb_uname = models.CharField(max_length=100)
    instagram = models.CharField(max_length=100)
    ig_uname = models.CharField(max_length=100)
    twitter = models.CharField(max_length=100)
    tw_uname = models.CharField(max_length=100)
    gitHub = models.CharField(max_length=100)
    gh_uname = models.CharField(max_length=100)
    linkedIn = models.CharField(max_length=100)
    ln_uname = models.CharField(max_length=100)
    about = models.CharField(max_length=200)
    eduName1 = models.CharField(max_length=100)
    eduYear1 = models.CharField(max_length=100)
    eduType1 = models.CharField(max_length=100)
    eduLoc1 = models.CharField(max_length=100)
    eduGPA1 = models.CharField(max_length=100, blank=True)
    eduName2 = models.CharField(max_length=100)
    eduYear2 = models.CharField(max_length=100)
    eduType2 = models.CharField(max_length=100)
    eduLoc2 = models.CharField(max_length=100)
    eduGPA2 = models.CharField(max_length=100, blank=True)
    eduName3 = models.CharField(max_length=100)
    eduYear3 = models.CharField(max_length=100)
    eduType3 = models.CharField(max_length=100)
    eduLoc3 = models.CharField(max_length=100)
    eduGPA3 = models.CharField(max_length=100, blank=True)
    skill1 = models.CharField(max_length=100)
    skillDesc1 = models.CharField(max_length=100)
    skill2 = models.CharField(max_length=100)
    skillDesc2 = models.CharField(max_length=100)
    skill3 = models.CharField(max_length=100)
    skillDesc3 = models.CharField(max_length=100)
    skill4 = models.CharField(max_length=100)
    skillDesc4 = models.CharField(max_length=100)
    skill5 = models.CharField(max_length=100)
    skillDesc5 = models.CharField(max_length=100)
    project1 = models.CharField(max_length=100)
    projectLink1 = models.CharField(max_length=100)
    project1Desc1 = models.CharField(max_length=100)
    project1Desc2 = models.CharField(max_length=100)
    projectDate1 = models.CharField(max_length=100)
    project2 = models.CharField(max_length=100)
    projectLink2 = models.CharField(max_length=100)
    project2Desc1 = models.CharField(max_length=100)
    project2Desc2 = models.CharField(max_length=100)
    projectDate2 = models.CharField(max_length=100)
    certName1 = models.CharField(max_length=100)
    certIssuer1 = models.CharField(max_length=100)
    certLink1 = models.CharField(max_length=100)
    certYear1 = models.CharField(max_length=100)
    certName2 = models.CharField(max_length=100)
    certIssuer2 = models.CharField(max_length=100)
    certLink2 = models.CharField(max_length=100)
    certYear2 = models.CharField(max_length=100)
    lang1 = models.CharField(max_length=100)
    langDesc1 = models.CharField(max_length=100)
    lang2 = models.CharField(max_length=100)
    langDesc2 = models.CharField(max_length=100)
    lang3 = models.CharField(max_length=100)
    langDesc3 = models.CharField(max_length=100)
    interests1 = models.CharField(max_length=100)
    interests2 = models.CharField(max_length=100)
    interests3 = models.CharField(max_length=100)
    interests4 = models.CharField(max_length=100)
    interests5 = models.CharField(max_length=100)

    def __str__(self):
        return self.fullname